### ISSUE TITLE
Supporting Sub-Menu

### ISSUE THREAD

**Issue by dwy6626** [dwy6626/dw-favored-blackburn#3]
Currently we don't support that, but the original theme support

### Problems

In https://github.com/yoshiharuyamashita/blackburn/pull/79, the `overflow-y` is set to `visible`, which will make sidebar unscrollable https://github.com/yoshiharuyamashita/blackburn/issues/92.

However, if set `overflow-y` to `auto`, it will let `overflow-x` become auto either. This is because the `visible` cannot use for scroll container.

https://www.w3.org/TR/css-overflow-3/

> visible
> There is no special handling of overflow, that is, the box’s content is rendered outside the box if positioned there. The box is not a scroll container.

The work branch is `feature/submenu` but I will not go ahead.

### Reference (Chinese)
- https://medium.com/%E6%8A%80%E8%A1%93%E7%AD%86%E8%A8%98/css-overflow-%E5%90%8C%E6%99%82%E8%A8%AD%E7%BD%AE-visible-%E8%88%87%E5%85%B6%E4%BB%96%E5%B1%AC%E6%80%A7%E8%A1%9D%E7%AA%81%E5%95%8F%E9%A1%8C-69b7bb70d065

**Comment by dwy6626** [comment]
For testing submenu in dw-favored-blackburn-example:

```toml
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "中文"
        pre = '<i class="fas fa-globe-asia fa-fw"></i>'
        weight = 100
        url = "zh"

      [[languages.en.menu.main]]
        name = "Posts"
        pre = "<i class='fas fa-user-circle fa-fw'></i>"
        weight = 2
        url = "about/"
        identifier = 'items'

      [[languages.en.menu.main]]
        name = "About"
        pre = "<i class='fas fa-user-circle fa-fw'></i>"
        weight = 3
        url = "about/"

      [[languages.en.menu.main]]
        name = "Lists"
        pre = "<i class='fas fa-list-ul fa-fw'></i>"
        weight = 10
        url = "post/"
        parent = 'items'

      [[languages.en.menu.main]]
        name = "Topics"
        pre = '<i class="fas fa-folder fa-fw"></i>'
        weight = 20
        url = "topics/"
        parent = 'items'

      [[languages.en.menu.main]]
        name = "Tags"
        pre = "<i class='fas fa-tags fa-fw'></i>"
        weight = 30
        url = "tags/"
```
